env:
# ENCRYPTED
  RCLONECONFIG_DRIVE: "ENCRYPTED[!eff6434f322510f592c6fd8f2bdb7e079ff9c791a7335aede1448b9cb2a4ad8edc6a5bffb4a1b1cd28b9fd5a5ef33595!]"
  TG_TOKEN: "ENCRYPTED[!53b0cd74189dbea265e1b856c502665eb0dca434d0b304ee2821441091c87aa6705e5ad93b0f3514f7c34e13f5d8efa1!]"
  TG_CHAT_ID: "ENCRYPTED[!30fe2176396a16b3a6482564ee7b41c352c1a4957721de8da64fb051740c7f188f55d6de964fe9d11c334d517db3a838!]"
  SF_USER: "ENCRYPTED[]"
  SF_PASS: "ENCRYPTED[]"

# FLAG
  WORKDIR: "/tmp"
  CIRRUS_CLONE_DEPTH: "1"

task:
  name: "BiancaProject Build"
  stateful: true
  timeout_in: 120m
  container:
    image: alanndz/ubuntu:22.04
    cpu: 8
    memory: 32G

  Memuat-ccache_script:
     - ls -l ./script/load_ccache.sh # Check permission status before
     - chmod +x ./script/load_ccache.sh # Add executable permission
     - ls -l ./script/load_ccache.sh # Check permission status after
     - chmod +x ./script/*.sh
     - chmod +x ./*.sh
     - ./script/load_ccache.sh

  Repo-pribadi_script:
     - git config --global user.name "Scharan459"
     - git config --global user.email "somanathcharan10@gmail.com"

  Sinkronasi-rom_script:
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Start sync Source"
     - ./script/sync.sh
     - curl -s https://api.telegram.org/bot$TG_TOKEN/sendMessage -d chat_id=$TG_CHAT_ID -d text="Sync Completed!"
     
  Membangun-rom_script:
     - ./script/building.sh
     
  Ccache-informasi_background_script:
     - set -e
     - export CCACHE_DIR=$WORKDIR/ccache
     - ccache -s

  Mengunggah-build_script:
     - ./script/ziping.sh
